name: CI

on:
  push:
    branches: [dev]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile
      - uses: actions/cache@v1
        id: cache-build
        with:
          path: '.'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

  validate:
    name: Validate
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/cache@v1
        id: restore-build
        with:
          path: '.'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn validate
        env:
          CI: true

  # TODO(kevanantha): test ci
